# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

github: [metadata]
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

# Site settings
title: Jeremy G. Kahn
email: jeremy@trochee.net
description: > # this means to ignore newlines until "baseurl:"
  Coding, natural language processing, "data science".
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: trochee
github_username:  jkahn

permalink: /:title/
# Build settings
markdown: kramdown

